---
fail-on-severity: "high"

exclude:
  - "./node_modules/**"
  - "./.git/**"
  - "./.github/**"
  - "./_site/**"

ignore:
  # Ignored by default; disputed and unwarranted CVE that causes Megalinter to fail
  # @link https://nvd.nist.gov/vuln/detail/CVE-2018-20225
  - vulnerability: CVE-2018-20225
