title: Technology Transformation Services
email: tts-info@gsa.gov
description: >- # this means to ignore newlines
  Every interaction with the public is an opportunity to improve trust in the government. For over 50 years, GSA has been working to improve access to government services. Today, GSA’s Technology Transformation Services (TTS) exists to design and deliver a digital government with and for the American people. We apply modern methodologies and technologies to improve the lives of the public and public servants. We help agencies make their services more accessible, efficient, and effective with modern applications, platforms, processes, personnel, and software solutions.

# Twitter handle. Only the handle, not the URL.
twitter: GSA_TTS

#################################################################
#
# Digital Analytics Program (DAP) configuration
#
# USAID   - Agency for International Development
# USDA    - Department of Agriculture
# DOC     - Department of Commerce
# DOD     - Department of Defense
# ED      - Department of Education
# DOE     - Department of Energy
# HHS     - Department of Health and Human Services
# DHS     - Department of Homeland Security
# HUD     - Department of Housing and Urban Development
# DOJ     - Department of Justice
# DOL     - Department of Labor
# DOS     - Department of State
# DOI     - Department of the Interior
# TREAS   - Department of the Treasury
# DOT     - Department of Transportation
# VA      - Department of Veterans Affairs
# EPA     - Environmental Protection Agency
# EOP     - Executive Office of the President
# GSA     - General Services Administration
# NASA    - National Aeronautics and Space Administration
# NARA    - National Archives and Records Administration
# NSF     - National Science Foundation
# NRC     - Nuclear Regulatory Commission
# OPM     - Office of Personnel Management
# USPS    - Postal Service
# SBA     - Small Business Administration
# SSA     - Social Security Administration
#
#################################################################
dap:
  # agency: your-agency

  # Optional
  # subagency: your-subagency

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: Home
    url: /
  - name: Join
    url: https://join.tts.gsa.gov
  - name: Handbook
    url: https://handbook.tts.gsa.gov
  - name: Offices
    children:
      - name: Presidential Innovation Fellows
        url: https://pif.gov
      - name: 18F
        url: https://18f.gsa.gov
      - name: Centers of Excellence
        url: https://coe.gsa.gov
      - name: Solutions
        url: "#main-content"
      - name: Regulatory and Oversight Systems
        url: "#main-content"
      - name: Integrated Award Environment
        url: "#main-content"

secondary_navigation:
  - name: Secondary link
    url: "#main-content"
  - name: Another secondary link
    url: "#main-content"
# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
# searchgov:
# Only change this if you're using a CNAME. Learn more here: https://search.gov/manual/cname.html
# endpoint: https://search.usa.gov

# Replace this with your search.gov account.
# affiliate: federalist-uswds-example

# Replace this with your access key.
# access_key: xX1gtb2RcnLbIYkHAcB6IaTRr4ZfN-p16ofcyUebeko=

# This renders the results within the page instead of sending to user to search.gov.
# inline: true

# This allows Search.gov to present relevant type-ahead search suggestions in your website's search box.
# If you do not want to present search suggestions, set this value to false.
# suggestions: true
##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################
