---
name: Content Update
about: Use this form to request content updates
projects:
  - GSA-TTS/54
labels:
  - "Content Update"
title: "Content Update"
body:
  - type: markdown
    attributes:
      value: |
        This form is used to request content updates.  We'll need
        to know the URL / address of the page that the content is
        on (or should be on), what the content currently says,
        and what the content should say.
    
  - id: url
    type: input
    attributes:
      label: URL    
      description: The URL of the page to be updated
      placeholder: URL
    validations:
      required: true

  - id: current
    type: textarea
    attributes:
      label: Current Content
      type: textarea
      description: This is what the page currently says
      placeholder: what the page says now

  - id: desired
    type: textarea
    attributes:
      label: Desired Contetn
      description: This is what you want the page to say
      placeholder: what the page should say
    validations:
      required: true

  - id: comments
    type: textarea
    attributes:
      label: Comments
      type: textarea
      description: Another other comments, formatting notes, not before / due by dates, etc.
      placeholder: comments

    
    
    
    
