---
## Comment out when doing local development
backend:
  name: github
  repo: GSA-TTS/tts.gsa.gov
  base_url: https://pages.cloud.gov
  auth_endpoint: external/auth/github
  preview_context: pages/build
  branch: main
  use_graphql: true

# #
# # Uncomment when doing local development on Netlify CMS
# # Run `npx netlify-cms-proxy-server` to start working locally
# # In another terminal, start the app with `npm start`
# # See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
# #

# backend:
#   name: git-gateway
# local_backend: true

media_folder: _img
public_folder: _img
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Main Pages
    name: pages
    folder: pages/
    create: true
    slug: "{{slug}}"
    fields:
      - name: "layout"
        label: "Layout"
        widget: "hidden"
        default: "layouts/page"

      - name: "permalink"
        label: "Page link"
        hint: "The URL this page will be accessible at."
        pattern: ['^.*\/$', "Must end with a slash"]
        widget: "string"
        default: "{{slug}}"

      - name: "title"
        label: "Title"
        widget: "string"

      - name: "body"
        label: "Body"
        widget: "markdown"
  - label: Site Alert
    name: hero-alert
    create: false
    format: "json"
    files:
      - label: "Hero Alert"
        name: "hero-alert"
        file: "_data/heroAlert.json"
        fields:
          - name: "message"
            label: "Message"
            widget: "string"
  - label: Join TTS Info Pages
    name: jointtspages
    folder: pages/jointts/
    create: true
    slug: "{{slug}}"
    fields:
      - name: "layout"
        label: "Layout"
        widget: "hidden"
        default: "layouts/page"

      - name: "permalink"
        label: "Page link"
        hint: "The URL this page will be accessible at."
        pattern: ['^.*\/$', "Must end with a slash"]
        widget: "string"
        default: "{{slug}}"

      - name: "title"
        label: "Title"
        widget: "string"

      - name: "body"
        label: "Body"
        widget: "markdown"

  - name: Services
    label: "Services Page"
    create: true
    format: "yaml"
    files:
      - label: "Services"
        name: "services"
        file: "_data/services.yaml"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            label_singular: "service"
            order: "{{fields.name}}"
            fields:
              - name: "name"
                label: "Name"
                widget: "string"

              - name: "link"
                label: "Link"
                widget: "string"

              - name: "link_alt_text"
                label: "Link Alt Text"
                widget: "string"

              - name: "logo"
                label: "Logo"
                widget: "image"

              - name: "logo_alt_text"
                label: "Logo Alt Text"
                widget: "string"

              - name: "category"
                label: "Category"
                widget: "string"

              - name: "description"
                label: "Description"
                widget: "text"

  - name: "Jobs"
    label: "Jobs Page"
    create: true
    folder: "pages/jointts/positions"
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"

      - name: "permalink"
        label: "Page Link"
        widget: "string"

      - name: "tags"
        label: "Tags"
        widget: "string"

      - name: "state"
        label: "Job State"
        widget: "string"

      - name: "job_post_type"
        label: "Job Post Type"
        widget: "string"

      - name: "role_name"
        label: "Role Name"
        widget: "string"

      - name: "opens"
        label: "Open Date"
        widget: "string"

      - name: "closes"
        label: "Close Date"
        widget: "string"

      - name: "weeks_open"
        label: "Weeks Open"
        widget: "number"

      - name: "location"
        label: "Location"
        widget: "string"

      - name: "gs_level"
        label: "GS Level"
        widget: "string"

      - name: "salary_min"
        label: "Mininum Salary"
        widget: "string"

      - name: "salary_max"
        label: "Maximum Salary"
        widget: "string"

      - name: "org"
        label: "Organization"
        widget: "string"

      - name: "contact_name"
        label: "Contact Name"
        widget: "string"

      - name: "contact_email"
        label: "Contact EMail"
        widget: "string"

      - name: "job_announcement_number"
        label: "Job Announcement Number"
        widget: "string"

      - name: "pd_job_title"
        label: "PD Job Title"
        widget: "string"

      - name: "num_vacancies"
        label: "Number of Vacancies"
        widget: "number"

      - name: "series"
        label: "series"
        widget: "string"

      - name: "apply_url"
        label: "Application URL"
        widget: "string"

      - name: "ohrm_contact_email"
        label: "OHRM Contact Email"
        widget: "string"

      - name: "ohrm_contact_name"
        label: "OHRM Contact Name"
        widget: "string"

      - name: "bargaining_unit"
        label: "Bargaining Unit"
        widget: "string"

      - name: "promotion_potential"
        label: "Promotion Potential"
        widget: "number"

      - name: "supervisory_status"
        label: "Supervisory Status"
        widget: "string"

      - name: "body"
        label: "Body"
        widget: "markdown"
