## Comment out when doing local development
backend:
  name: github
  repo: GSA-TTS/tts.gsa.gov
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main
  use_graphql: true

##
## Uncomment when doing local development on Netlify CMS
## Run `npx netlify-cms-proxy-server` to start working locally
## In another terminal, start the app with `npm start`
## See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
##

# backend:
#   name: git-gateway
# local_backend: true

media_folder: _img
public_folder: _img
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Posts
    name: posts
    folder: posts/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'layouts/post'}
      - {label: 'Tags', name: 'tags', widget: 'hidden', default: ['posts']}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'YYYY-MM-DD',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: false
        }
      - {
        label: "Image",
        name: "image",
        widget: "image",
        allow_multiple: false,
        required: false
        }
      - {
        label: "Image Alt Text",
        name: "image_alt_text",
        widget: "string",
        required: false
        }
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Services Page"
    name: Services
    create: true
    format: "yaml"
    files:
      - label: "Services"
        name: "services"
        file: "_data/services.yaml"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            label_singular: "service"
            order: "{{fields.name}}"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: Link Alt Text, name: link_alt_text, widget: string}
              - {label: Logo, name: logo, widget: image}
              - {label: Logo Alt Text, name: logo_alt_text, widget: string}
              - {label: Description, name: description, widget: text}
