---
name: Build and Test

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3

      - name: Use Node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # pin@v3
        with:
          node-version: "17.x"

      - name: Install NPM dependencies
        run: npm install

      - name: Build site
        run: npm run build
#      - name: Run tests
#        run: npm run test
